import test from 'node:test';
import assert from 'node:assert/strict';
import * as core from '../src/core.js';

const EXPECTED_EXPORTS = [
  'CSV_HEADERS',
  'DISPLAY_CURRENCY_UAH',
  'DISPLAY_CURRENCY_USD',
  'SCREEN_CATEGORY_MERGE',
  'SCREEN_CHARTS',
  'SCREEN_DATA',
  'SCREEN_DATA_OPS',
  'SCREEN_FX_RATES',
  'SCREEN_TAGS',
  'STORAGE_KEY',
  'STORAGE_VERSION',
  'TAG_GROUP_INVALID_LABEL',
  'TAG_GROUP_NO_TAG_LABEL',
  'USD_RATE_COVERAGE_DAYS',
  'applyBulkTagMutation',
  'buildCategoryMergeRuntime',
  'buildCategoryPieDatasetAbsoluteNet',
  'buildCategoryPieDatasetUAHAbsoluteNet',
  'buildDedupId',
  'buildFileFingerprint',
  'buildPiePalette',
  'buildSourceFullCategory',
  'buildTagGroupPieDatasetAbsoluteNet',
  'buildTagGroupPieDatasetUAHAbsoluteNet',
  'buildTagPieDatasetAbsoluteNet',
  'buildTagPieDatasetUAHAbsoluteNet',
  'buildUsdCoverageReport',
  'buildUsdCoverageReportForRowsById',
  'computeEffectiveRow',
  'countSelectedCalendarDays',
  'createEmptyState',
  'displayDateTime',
  'ensureCategoryMergeModel',
  'ensureCategoryMergeRuntime',
  'fileNameToMainCategory',
  'formatDateInputValue',
  'formatLocalDateTime',
  'formatMoney',
  'formatTagsInput',
  'getRowConversionForDisplayCurrency',
  'hashFNV1a',
  'matchesFilter',
  'mergeImportedRow',
  'normalizeCurrency',
  'normalizeDateForId',
  'normalizeDisplayCurrency',
  'normalizeFilterDate',
  'normalizeImportedRow',
  'normalizeNumericString',
  'normalizeTagGroupIndex',
  'normalizeTags',
  'parseCategoryMergeRulesText',
  'parseCsvText',
  'parseExpenseCsv',
  'parseLocalDateTime',
  'parseManualUsdRatesText',
  'parseNumber',
  'parseStateSnapshotJson',
  'parseTagGroupsText',
  'recomputeDerivedRows',
  'resolveRate',
  'resolveUsdRate',
  'sanitizeLoadedState',
  'sortRowsByDateDesc',
  'summarizeRowsByDisplayCurrency',
  'summarizeUah',
  'validateRowTagsAgainstGroups',
  'validateStateSnapshot'
];

test('core.js export surface remains stable', () => {
  const names = Object.keys(core).sort();
  assert.deepEqual(names, EXPECTED_EXPORTS);
});
